# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FIRMarkdown' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FIRMarkdown
  # YYKit相关
  pod 'YYCategories', '~> 1.0.4'
  pod 'YYText', '~> 1.0.7'
  # autolayout
  pod 'Masonry'

end
